"use client";

import { createContext, useContext, useState, useEffect } from "react";

const AppContext = createContext();

const translations = {
  en: {
    // General / Actions
    cancel: "Cancel",
    submit: "Submit",
    save: "Save",
    logout: "Logout",
    search: "Search...",
    export: "Export Data",
    all: "All",
    status: "Status",
    date: "Date",
    loading: "Loading...",
    
    // Login
    loginHeader: "ApexLoan",
    loginSub: "Sign in to access your loan management dashboard",
    email: "Email Address",
    password: "Password",
    rememberMe: "Remember me",
    forgotPass: "Forgot password?",
    signIn: "Sign In",
    signingIn: "Signing in...",
    demoMode: "Demo Mode: You can enter any valid email and a 6+ character password to log in.",
    emailReq: "Email address is required",
    emailInvalid: "Please enter a valid email address",
    passwordReq: "Password is required",
    passwordMin: "Password must be at least 6 characters",

    // Sidebar
    enterprisePlatform: "ENTERPRISE PLATFORM",
    navDashboard: "Dashboard",
    navLoans: "Loans",
    navRepayments: "Repayments",
    navCustomers: "Customers",
    navCases: "Cases",
    navSettings: "Settings",

    // Header / Welcome
    welcomeAdmin: "Welcome back, Administrator",
    sysAdmin: "Systems Admin",
    
    // Overview Dashboard
    sysOverview: "System Overview",
    sysOverviewSub: "Monitor and manage active loan portfolios, collections, and borrower submissions.",
    newLoanApp: "New Loan Application",
    newLoanAppShort: "+ New Loan",
    cashFlowTrend: "Cash Flow Trend",
    cashFlowTrendSub: "Compare monthly disbursements against collections.",
    disbursements: "Disbursements",
    collections: "Collections",
    loanAllocation: "Loan Allocation",
    loanAllocationSub: "Disbursement volume by loan type.",
    totalLoansText: "Total Loans",
    recentApp: "Recent Loan Applications",
    recentAppSub: "Overview of loan submissions and their processing statuses.",
    searchBorrowerId: "Search borrower or ID...",
    allStatuses: "All Statuses",
    noRecords: "No records match your query.",

    // Stat Cards
    totalDisbursed: "Total Disbursed",
    activeLoansCount: "Active Loans",
    collectionRate: "Collection Rate",
    defaultRate: "Default Rate",
    totalCapitalOut: "Total Capital Out",
    approvedLoans: "Approved Loans",
    pendingReview: "Pending Review",
    riskAssessment: "Risk Assessment",
    totalReceived: "Total Received",
    settledCleared: "Settled & Cleared",
    processingQueue: "Processing Queue",
    failedReceipts: "Failed Receipts",
    allBorrowers: "All Borrowers",
    activeAccounts: "Active Accounts",
    avgScore: "Average Score",
    newBorrowers: "New Borrowers",
    vsLastMonth: "vs last month",
    lowRisk: "Low (1.1%)",
    avgScoreValue: "709 (Good)",
    newBorrowersValue: "+12 this week",

    // Table Headers
    id: "ID",
    borrower: "Borrower",
    loanType: "Loan Type",
    amount: "Amount",
    rate: "Rate",
    term: "Term",

    // Statuses
    Approved: "Approved",
    Pending: "Pending",
    Repaid: "Repaid",
    Overdue: "Overdue",
    Failed: "Failed",
    Processing: "Processing",
    Active: "Active",
    Inactive: "Inactive",

    // Loans View
    loansRegistry: "Loan Registry",
    loansRegistrySub: "Register new agreements, evaluate outstanding debt risk, and review active loans.",
    searchIdBorrower: "Search by ID or Borrower name...",
    borrowerName: "Borrower Name",
    principalAmt: "Principal Amount (₹)",
    interestRate: "Interest Rate (%)",
    termDuration: "Term Duration (Months)",
    submitApp: "Submit Application",

    // Repayments View
    repaymentHistory: "Repayment History",
    repaymentHistorySub: "Log received payments, verify clearing transactions, and check outstanding schedules.",
    recordRepay: "Record Repayment",
    recordRepayReceipt: "Record Repayment Receipt",
    searchTxLoanName: "Search by Transaction, Loan ID, or name...",
    paymentMode: "Payment Mode",
    allMethods: "All Methods",
    bankTransfer: "Bank Transfer",
    achDebits: "ACH Debits",
    cardPayment: "Card Payment",
    txId: "Transaction ID",
    loanRefId: "Loan Reference ID",
    amountPaid: "Amount Paid",
    confirmRepay: "Confirm Repayment",

    // Customers View
    borrowerDir: "Borrower Directory",
    borrowerDirSub: "Manage customer files, monitor active debt portfolios, and track credit performance.",
    searchIdEmailName: "Search by ID, email, or name...",
    custId: "Customer ID",
    phoneNum: "Phone Number",
    creditScore: "Credit Score",
    activeAgreements: "Active Agreements",
    totalDebtBal: "Total Debt Balance",
    accStatus: "Account Status",

    // Settings View
    platformConfig: "Platform Configuration",
    platformConfigSub: "Fine-tune loan calculation constraints, update administrator profiles, and configure security rules.",
    loanEnginePolicies: "Loan Engine Policies",
    baseRate: "Base Annual Interest Rate (%)",
    maxTenure: "Max Tenure Limit (Months)",
    lateRepayFee: "Late Repayment Fee (₹)",
    adminDetails: "Administrator Details",
    fullName: "Full Display Name",
    securityAlerts: "Security & Alerts",
    twoFactor: "2-Factor Auth",
    twoFactorSub: "Validate via authenticator app.",
    dailyAuditLog: "Daily Audit Log",
    dailyAuditLogSub: "Receive summaries via email.",
    sessionExpiryMin: "Session Expiry (Minutes)",
    saveConfig: "Save Configuration",
    configSuccess: "Configuration details updated successfully.",
    settingsNote: "Modifying loan parameters applies instantly to all newly created loan applications but will not change pre-approved rates in the registry.",
    timeout15: "15 Minutes",
    timeout30: "30 Minutes",
    timeout60: "60 Minutes",
    timeout120: "2 Hours",
    navNotifications: "Notifications",
    notifications: "Notifications",
    notificationsSub: "Review recent system alerts, loan approvals, and repayment updates.",
    markAllRead: "Mark all as read",
    clearAll: "Clear all",
    noNotifications: "No notifications found.",
    info: "Info",
    alert: "Alert",
    success: "Success",
    warning: "Warning",
    navAnalytics: "Analytics",
    analyticsTitle: "Analytics & Intelligence",
    analyticsSub: "Track historical loan performances, active default risk assessments, and system margins.",
    earningsGrowth: "Earnings Growth",
    earningsGrowthSub: "Interest yield returns compared against targets.",
    riskProfile: "Credit Risk Profile",
    riskProfileSub: "Borrower population score distributions.",
    yieldTarget: "Yield Target",
    riskAverage: "Risk Average",
    navCalculator: "Calculator",
    calculatorTitle: "Loan Calculator & Amortization",
    calculatorSub: "Simulate interest margins, monthly payments, and complete amortization schedules.",
    calculate: "Calculate Amortization",
    monthlyRepayment: "Monthly Repayment",
    totalInterest: "Total Interest",
    totalRepayment: "Total Repayment",
    amortizationSchedule: "Amortization Schedule",
    month: "Month",
    principalPaid: "Principal Paid",
    interestPaid: "Interest Paid",
    remainingBalance: "Remaining Balance",
    
    // Landing Page
    landingTitle: "Next-Generation Enterprise Loan Management",
    landingSub: "ApexLoan empowers financial institutions with interactive amortization simulators, real-time analytics dashboards, and secure credit risk evaluations.",
    landingHeroCTA: "Go to Dashboard",
    landingHeroLogin: "Employee Sign In",
    landingHeroScroll: "Try Simulator",
    featuresSectionTitle: "Enterprise-Grade Lending Suite",
    featuresSectionSub: "Explore tools crafted for institutional credit operations, interest margin optimization, and risk management.",
    featCalcTitle: "Interactive Calculator",
    featCalcDesc: "Perform instant compound interest simulations and view full monthly amortization schedules.",
    featAnalyticsTitle: "Portfolio Analytics",
    featAnalyticsDesc: "Track capital velocity, default risk distributions, and yields against target forecasts.",
    featThemeTitle: "Responsive Dark/Light",
    featThemeDesc: "Seamless theme adjustments for comfortable viewing across all desktop and mobile devices.",
    featSecurityTitle: "Secured Audit Log",
    featSecurityDesc: "Advanced session controls, administrator alerts, and strict system logging.",
    statActiveLoans: "Active Portfolios",
    statDisbursed: "Capital Disbursed",
    statRate: "Collection rate",
    statQueue: "Processing Queue",
    quickSimulatorTitle: "Instant Loan Simulator",
    quickSimulatorSub: "Enter parameters to estimate monthly payments and total payback amounts instantly.",
    loanAmount: "Principal Amount (₹)",
    annualInterestRate: "Annual Interest Rate (%)",
    loanTerm: "Term Duration (Months)",
    estMonthlyPayment: "Estimated Monthly Repayment",
    estTotalPayback: "Total Repayment Value",
    estTotalInterest: "Total Interest Yield",
    ctaBannerTitle: "Optimize Your Loan Portfolio Operations",
    ctaBannerSub: "Sign in with your administration credentials or start simulating agreements to experience the platform.",

    // Attendance Module
    navAttendance: "Attendance",
    attendanceTitle: "Agent Attendance",
    attendanceSub: "Track daily field duty check-ins for all recovery agents by zone.",
    markAttendance: "Mark Attendance",
    totalEmployees: "Total Agents",
    presentToday: "On Duty Today",
    absentToday: "Off Duty Today",
    lateArrivals: "Late to Field",
    employeeId: "Agent ID",
    employeeName: "Agent Name",
    department: "Zone",
    checkIn: "Check-In",
    checkOut: "Check-Out",
    hoursWorked: "Hours Worked",
    attendanceStatus: "Status",
    Present: "Present",
    Absent: "Absent",
    Late: "Late",
    Leave: "On Leave",
    filterDate: "Filter by Date",
    confirmAttendance: "Confirm Attendance",
    attendanceNote: "Field check-in data is auto-synced with the mobile agent app every 10 minutes.",

    // Working Hours Module
    navWorkingHours: "Working Hours",
    workingHoursTitle: "Agent Field Hours",
    workingHoursSub: "Monitor weekly field hours, overtime, and undertime across recovery zones.",
    avgDailyHours: "Avg Daily Hours",
    totalOvertime: "Total Overtime Hrs",
    undertimeAlerts: "Undertime Alerts",
    weekTotal: "This Week Total",
    weeklyBreakdown: "Weekly Breakdown",
    weeklyBreakdownSub: "Zone-level field hours for the current week.",
    editHours: "Edit Hours",
    overtime: "Overtime",
    undertime: "Undertime",
    normal: "Normal",
    saveHours: "Save Hours",
    mon: "Mon", tue: "Tue", wed: "Wed", thu: "Thu", fri: "Fri",

    // Employee Tracking Module
    navTracking: "Employee Tracking",
    trackingTitle: "Agent Live Tracking",
    trackingSub: "Real-time visibility into recovery agents' field locations and active case assignments.",
    totalStaff: "Total Agents",
    onSite: "On-Site",
    remote: "Remote",
    onLeaveCount: "On Leave",
    lastSeen: "Last Seen",
    location: "Location",
    role: "Role",
    updateLocation: "Update Status",
    filterDept: "Filter by Zone",
    filterStatus: "Filter by Status",
    allDepts: "All Zones",
    allStatuses2: "All Statuses",
    OnSite: "On-Site",
    Remote: "Remote",
    OnLeave: "On Leave",
    saveLocation: "Save Location",
    mapView: "Map View",
    gridView: "Grid View",

    // Customer Feedback Module
    navFeedback: "Customer Feedback",
    feedbackTitle: "Recovery Visit Logs",
    feedbackSub: "Agent visit outcomes for each borrower contact attempt. Log collections, promises, and escalations.",
    totalFeedback: "Total Visits",
    avgRating: "Avg Recovery",
    positiveRate: "Collected Rate",
    pendingReviews: "Pending Follow-up",
    addFeedback: "Log Visit",
    customerName: "Borrower Name",
    loanRefIdFb: "Loan ID",
    rating: "Amount (₹)",
    category: "Outcome",
    comment: "Agent Notes",
    feedbackDate: "Visit Date",
    feedbackStatus: "Status",
    Resolved: "Collected",
    Pending2: "Promise to Pay",
    Archived: "Escalated",
    Service: "Full Payment",
    Product: "Partial Payment",
    Process: "Promise to Pay",
    Staff: "Refused",
    allCategories: "All Outcomes",
    resolveFeedback: "Mark Collected",
    archiveFeedback: "Escalate",
    submitFeedback: "Log Visit",
    feedbackPlaceholder: "Describe borrower response, conditions, next steps...",

    // ── Recovery Dashboard ─────────────────────────────────
    recoveryOverview: "Recovery Operations Overview",
    recoveryOverviewSub: "Monitor active recovery agents, overdue portfolios, and daily collection performance.",
    assignCase: "Assign Recovery Case",
    totalOverduePortfolio: "Overdue Portfolio",
    recoveredThisMonth: "Recovered This Month",
    recoveryRate: "Recovery Rate",
    activeAgentsInField: "Agents in Field",
    recoveryVsTarget: "Recovery vs Target",
    recoveryVsTargetSub: "Monthly amounts collected vs recovery targets.",
    targetRecovery: "Target",
    actualRecovery: "Collected",
    casesByStatus: "Cases by Recovery Status",
    casesByStatusSub: "Breakdown of all assigned recovery cases.",
    totalCases: "Total Cases",
    agentSummaryTitle: "Agents on Duty Today",
    agentSummaryLink: "View All Agents",

    // ── Recovery Cases Table ───────────────────────────────
    recoveryCase: "Recovery Cases",
    recoveryCaseSub: "Overdue loan cases assigned to field recovery agents for collection.",
    daysOverdue: "Days Overdue",
    assignedAgent: "Assigned Agent",
    recoveryStatus: "Recovery Status",
    lastContact: "Last Contact",
    Recovered: "Recovered",
    InProgress: "In Progress",
    PendingContact: "Pending Contact",
    Escalated: "Escalated",
    allRecoveryStatuses: "All Statuses",

    // ── Recovery Agents Module ─────────────────────────────
    navRecoveryAgents: "Recovery Agents",
    recoveryAgentsTitle: "Recovery Agents",
    recoveryAgentsSub: "Manage field recovery agents, their zones, caseloads, and collection performance.",
    addAgent: "Add Agent",
    agentId: "Agent ID",
    agentName: "Agent Name",
    zone: "Zone",
    casesAssigned: "Cases Assigned",
    recoveredAmount: "Recovered (₹)",
    successRate: "Success Rate",
    agentStatus: "Status",
    totalAgents: "Total Agents",
    activeAgents: "Active Agents",
    topPerformer: "Top Performer",
    avgSuccessRate: "Avg Success Rate",
    saveAgent: "Save Agent",
    contactNumber: "Contact Number",
    assignedZone: "Assigned Zone",
    joinDate: "Join Date",
  },
  hi: {
    // General / Actions
    cancel: "रद्द करें",
    submit: "जमा करें",
    save: "सुरक्षित करें",
    logout: "लॉगआउट",
    search: "खोजें...",
    export: "डेटा निर्यात करें",
    all: "सभी",
    status: "स्थिति",
    date: "दिनांक",
    loading: "लोड हो रहा है...",

    // Login
    loginHeader: "एपेक्सलोन",
    loginSub: "अपने ऋण प्रबंधन डैशबोर्ड तक पहुंचने के लिए साइन इन करें",
    email: "ईमेल पता",
    password: "पासवर्ड",
    rememberMe: "मुझे याद रखें",
    forgotPass: "पासवर्ड भूल गए?",
    signIn: "साइन इन करें",
    signingIn: "साइन इन हो रहा है...",
    demoMode: "डेमो मोड: लॉग इन करने के लिए आप कोई भी मान्य ईमेल और 6+ वर्णों का पासवर्ड डाल सकते हैं।",
    emailReq: "ईमेल पता आवश्यक है",
    emailInvalid: "कृपया एक मान्य ईमेल पता दर्ज करें",
    passwordReq: "पासवर्ड आवश्यक है",
    passwordMin: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए",

    // Sidebar
    enterprisePlatform: "एंटरप्राइज प्लेटफॉर्म",
    navDashboard: "डैशबोर्ड",
    navLoans: "ऋण सूची",
    navRepayments: "पुनर्भुगतान",
    navCustomers: "ग्राहक",
    navCases: "मामले",
    navSettings: "सेटिंग्स",

    // Header / Welcome
    welcomeAdmin: "वापसी पर स्वागत है, प्रशासक",
    sysAdmin: "सिस्टम प्रशासक",

    // Overview Dashboard
    sysOverview: "सिस्टम अवलोकन",
    sysOverviewSub: "सक्रिय ऋण पोर्टफोलियो, संग्रह और उधारकर्ता के आवेदनों की निगरानी और प्रबंधन करें।",
    newLoanApp: "नया ऋण आवेदन",
    newLoanAppShort: "+ नया ऋण",
    cashFlowTrend: "कैश फ्लो ट्रेंड",
    cashFlowTrendSub: "संग्रह के मुकाबले मासिक ऋण वितरण की तुलना करें।",
    disbursements: "ऋण वितरण",
    collections: "ऋण संग्रह",
    loanAllocation: "ऋण आवंटन",
    loanAllocationSub: "ऋण प्रकार के अनुसार वितरण मात्रा।",
    totalLoansText: "कुल ऋण",
    recentApp: "हाल के ऋण आवेदन",
    recentAppSub: "ऋण आवेदनों और उनकी प्रसंस्करण स्थितियों का अवलोकन।",
    searchBorrowerId: "उधारकर्ता या आईडी खोजें...",
    allStatuses: "सभी स्थितियाँ",
    noRecords: "आपकी खोज से मेल खाता कोई रिकॉर्ड नहीं मिला।",

    // Stat Cards
    totalDisbursed: "कुल वितरित",
    activeLoansCount: "सक्रिय ऋण",
    collectionRate: "संग्रह दर",
    defaultRate: "डिफ़ॉल्ट दर",
    totalCapitalOut: "कुल पूंजी बाहर",
    approvedLoans: "स्वीकृत ऋण",
    pendingReview: "समीक्षा लंबित",
    riskAssessment: "जोखिम मूल्यांकन",
    totalReceived: "कुल प्राप्त",
    settledCleared: "निपटारा और स्वीकृत",
    processingQueue: "प्रसंस्करण कतार",
    failedReceipts: "विफल रसीदें",
    allBorrowers: "सभी उधारकर्ता",
    activeAccounts: "सक्रिय खाते",
    avgScore: "औसत स्कोर",
    newBorrowers: "नए उधारकर्ता",
    vsLastMonth: "पिछले महीने की तुलना में",
    lowRisk: "कम (1.1%)",
    avgScoreValue: "709 (अच्छा)",
    newBorrowersValue: "इस सप्ताह +12",

    // Table Headers
    id: "आईडी",
    borrower: "उधारकर्ता",
    loanType: "ऋण प्रकार",
    amount: "राशि",
    rate: "दर",
    term: "अवधि",

    // Statuses
    Approved: "स्वीकृत",
    Pending: "लंबित",
    Repaid: "भुगतान किया",
    Overdue: "अतिदेय",
    Failed: "विफल",
    Processing: "प्रक्रिया में",
    Active: "सक्रिय",
    Inactive: "निष्क्रिय",

    // Loans View
    loansRegistry: "ऋण रजिस्ट्री",
    loansRegistrySub: "नए समझौतों को पंजीकृत करें, बकाया ऋण जोखिम का मूल्यांकन करें, और सक्रिय ऋणों की समीक्षा करें।",
    searchIdBorrower: "आईडी या उधारकर्ता के नाम से खोजें...",
    borrowerName: "उधारकर्ता का नाम",
    principalAmt: "मूल राशि (₹)",
    interestRate: "ब्याज दर (%)",
    termDuration: "अवधि सीमा (महीने)",
    submitApp: "आवेदन जमा करें",

    // Repayments View
    repaymentHistory: "पुनर्भुगतान इतिहास",
    repaymentHistorySub: "प्राप्त भुगतानों को दर्ज करें, समाशोधन लेनदेन की पुष्टि करें, और बकाया शेड्यूल की जांच करें।",
    recordRepay: "पुनर्भुगतान दर्ज करें",
    recordRepayReceipt: "पुनर्भुगतान रसीद दर्ज करें",
    searchTxLoanName: "लेनदेन, ऋण आईडी, या नाम से खोजें...",
    paymentMode: "भुगतान का प्रकार",
    allMethods: "सभी विधियां",
    bankTransfer: "बैंक ट्रांसफर",
    achDebits: "एसीएच डेबिट",
    cardPayment: "कार्ड भुगतान",
    txId: "लेनदेन आईडी",
    loanRefId: "ऋण संदर्भ आईडी",
    amountPaid: "भुगतान की गई राशि",
    confirmRepay: "पुनर्भुगतान की पुष्टि करें",

    // Customers View
    borrowerDir: "उधारकर्ता निर्देशिका",
    borrowerDirSub: "ग्राहक फ़ाइलों का प्रबंधन करें, सक्रिय ऋण पोर्टफोलियो की निगरानी करें और क्रेडिट प्रदर्शन को ट्रैक करें।",
    searchIdEmailName: "आईडी, ईमेल या नाम से खोजें...",
    custId: "ग्राहक आईडी",
    phoneNum: "फ़ोन नंबर",
    creditScore: "क्रेडिट स्कोर",
    activeAgreements: "सक्रिय समझौते",
    totalDebtBal: "कुल ऋण शेष",
    accStatus: "खाता स्थिति",

    // Settings View
    platformConfig: "प्लेटफॉर्म विन्यास",
    platformConfigSub: "ऋण गणना सीमाओं को ठीक करें, प्रशासक प्रोफाइल अपडेट करें, और सुरक्षा नियमों को कॉन्फ़िगर करें।",
    loanEnginePolicies: "ऋण इंजन नीतियां",
    baseRate: "मूल वार्षिक ब्याज दर (%)",
    maxTenure: "अधिकतम अवधि सीमा (महीने)",
    lateRepayFee: "विलंब पुनर्भुगतान शुल्क (₹)",
    adminDetails: "प्रशासक का विवरण",
    fullName: "पूरा नाम",
    securityAlerts: "सुरक्षा और अलर्ट",
    twoFactor: "द्वि-कारक प्रमाणीकरण (2FA)",
    twoFactorSub: "प्रमाणक ऐप के माध्यम से पुष्टि करें।",
    dailyAuditLog: "दैनिक ऑडिट लॉग",
    dailyAuditLogSub: "ईमेल के माध्यम से सारांश प्राप्त करें।",
    sessionExpiryMin: "सत्र समाप्ति (मिनट)",
    saveConfig: "विन्यास सुरक्षित करें",
    configSuccess: "विन्यास विवरण सफलतापूर्वक अपडेट किया गया।",
    settingsNote: "ऋण मापदंडों में बदलाव तुरंत नए बनाए गए ऋण आवेदनों पर लागू होता है लेकिन रजिस्ट्री में पूर्व-स्वीकृत दरों को नहीं बदलेगा।",
    timeout15: "15 मिनट",
    timeout30: "30 मिनट",
    timeout60: "60 मिनट",
    timeout120: "2 घंटे",
    navNotifications: "अधिसूचनाएं",
    notifications: "अधिसूचनाएं",
    notificationsSub: "हाल के सिस्टम अलर्ट, ऋण स्वीकृति और पुनर्भुगतान अपडेट की समीक्षा करें।",
    markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
    clearAll: "सभी साफ़ करें",
    noNotifications: "कोई अधिसूचना नहीं मिली।",
    info: "सूचना",
    alert: "अलर्ट",
    success: "सफलता",
    warning: "चेतावनी",
    navAnalytics: "विश्लेषण",
    analyticsTitle: "विश्लेषण और इंटेलिजेंस",
    analyticsSub: "ऐतिहासिक ऋण प्रदर्शन, सक्रिय डिफ़ॉल्ट जोखिम आकलन और सिस्टम मार्जिन को ट्रैक करें।",
    earningsGrowth: "कमाई में वृद्धि",
    earningsGrowthSub: "लक्ष्यों की तुलना में ब्याज उपज रिटर्न।",
    riskProfile: "क्रेडिट जोखिम प्रोफ़ाइल",
    riskProfileSub: "उधारकर्ता जनसंख्या स्कोर वितरण।",
    yieldTarget: "उपज लक्ष्य",
    riskAverage: "औसत जोखिम",
    navCalculator: "कैलकुलेटर",
    calculatorTitle: "ऋण कैलकुलेटर और परिशोधन",
    calculatorSub: "ब्याज मार्जिन, मासिक भुगतान और पूर्ण परिशोधन तालिकाओं का अनुकरण करें।",
    calculate: "परिशोधन की गणना करें",
    monthlyRepayment: "मासिक पुनर्भुगतान",
    totalInterest: "कुल ब्याज",
    totalRepayment: "कुल पुनर्भुगतान",
    amortizationSchedule: "परिशोधन अनुसूची",
    month: "महीना",
    principalPaid: "भुगतान किया गया मूल",
    interestPaid: "भुगतान किया गया ब्याज",
    remainingBalance: "शेष राशि",

    // Landing Page
    landingTitle: "अगली पीढ़ी का एंटरप्राइज ऋण प्रबंधन",
    landingSub: "एपेक्सलोन वित्तीय संस्थानों को इंटरैक्टिव परिशोधन सिमुलेटर, वास्तविक समय विश्लेषण डैशबोर्ड और सुरक्षित क्रेडिट जोखिम मूल्यांकन के साथ सशक्त बनाता है।",
    landingHeroCTA: "डैशबोर्ड पर जाएं",
    landingHeroLogin: "कर्मचारी साइन इन",
    landingHeroScroll: "सिम्युलेटर आज़माएं",
    featuresSectionTitle: "एंटरप्राइज-ग्रेड ऋण सुइट",
    featuresSectionSub: "संस्थागत क्रेडिट संचालन, ब्याज मार्जिन अनुकूलन और जोखिम प्रबंधन के लिए तैयार किए गए उपकरणों का अन्वेषण करें।",
    featCalcTitle: "इंटरैक्टिव कैलकुलेटर",
    featCalcDesc: "त्वरित चक्रवृद्धि ब्याज सिमुलेशन करें और पूर्ण मासिक भुगतान अनुसूची देखें।",
    featAnalyticsTitle: "पोर्टफोलियो विश्लेषण",
    featAnalyticsDesc: "पूंजी वेग, डिफ़ॉल्ट जोखिम वितरण और लक्ष्य पूर्वानुमानों के विरुद्ध आय को ट्रैक करें।",
    featThemeTitle: "उत्तरदायी डार्क/लाइट",
    featThemeDesc: "सभी डेस्कटॉप और मोबाइल उपकरणों पर आरामदायक देखने के लिए निर्बाध थीम समायोजन।",
    featSecurityTitle: "सुरक्षित ऑडिट लॉग",
    featSecurityDesc: "उन्नत सत्र नियंत्रण, प्रशासक अलर्ट और सख्त सिस्टम लॉगिंग।",
    statActiveLoans: "सक्रिय पोर्टफोलियो",
    statDisbursed: "पूंजी वितरित की गई",
    statRate: "संग्रह दर",
    statQueue: "प्रसंस्करण कतार",
    quickSimulatorTitle: "त्वरित ऋण सिम्युलेटर",
    quickSimulatorSub: "मासिक भुगतान और कुल चुकौती राशि का तुरंत अनुमान लगाने के लिए विवरण दर्ज करें।",
    loanAmount: "मूल ऋण राशि (₹)",
    annualInterestRate: "वार्षिक ब्याज दर (%)",
    loanTerm: "ऋण अवधि (महीने)",
    estMonthlyPayment: "अनुमानित मासिक पुनर्भुगतान",
    estTotalPayback: "कुल चुकौती मूल्य",
    estTotalInterest: "कुल ब्याज आय",
    ctaBannerTitle: "अपने ऋण पोर्टफोलियो संचालन को अनुकूलित करें",
    ctaBannerSub: "प्लेटफ़ॉर्म का अनुभव करने के लिए अपने व्यवस्थापक क्रेडेंशियल के साथ साइन इन करें या अनुबंधों का अनुकरण शुरू करें।",

    markAttendance: "उपस्थिति दर्ज करें",
    totalEmployees: "कुल एजेंट",
    presentToday: "आज ड्यूटी पर",
    absentToday: "आज ऑफ ड्यूटी",
    lateArrivals: "देर से फील्ड पहुंचे",
    employeeId: "एजेंट आईडी",
    employeeName: "एजेंट का नाम",
    department: "जोन",
    checkIn: "चेक-इन",
    checkOut: "चेक-आउट",
    hoursWorked: "काम के घंटे",
    attendanceStatus: "स्थिति",
    Present: "उपस्थित",
    Absent: "अनुपस्थित",
    Late: "देर से",
    Leave: "छुट्टी पर",
    filterDate: "तिथि से फ़िल्टर करें",
    confirmAttendance: "उपस्थिति पुष्टि करें",
    attendanceNote: "फील्ड चेक-इन डेटा हर 10 मिनट में मोबाइल एजेंट ऐप के साथ स्वतः सिंक होता है।",

    // कार्य घंटे मॉड्यूल
    navWorkingHours: "कार्य घंटे",
    workingHoursTitle: "एजेंट फील्ड घंटे",
    workingHoursSub: "रिकवरी जोन में साप्ताहिक फील्ड घंटे, ओवरटाइम और कम समय की निगरानी करें।",
    avgDailyHours: "औसत दैनिक घंटे",
    totalOvertime: "कुल ओवरटाइम घंटे",
    undertimeAlerts: "कम समय के अलर्ट",
    weekTotal: "इस सप्ताह कुल",
    weeklyBreakdown: "साप्ताहिक विवरण",
    weeklyBreakdownSub: "वर्तमान सप्ताह के लिए जोन-स्तरीय फील्ड घंटे।",
    editHours: "घंटे संपादित करें",
    overtime: "ओवरटाइम",
    undertime: "कम समय",
    normal: "सामान्य",
    saveHours: "घंटे सुरक्षित करें",
    mon: "सोम", tue: "मंगल", wed: "बुध", thu: "गुरु", fri: "शुक्र",

    // कर्मचारी ट्रैकिंग मॉड्यूल
    navTracking: "कर्मचारी ट्रैकिंग",
    trackingTitle: "एजेंट लाइव ट्रैकिंग",
    trackingSub: "रिकवरी एजेंटों के फील्ड स्थानों और सक्रिय केस असाइनमेंट में रीयल-टाइम दृश्यता।",
    totalStaff: "कुल एजेंट",
    onSite: "साइट पर",
    remote: "दूरस्थ",
    onLeaveCount: "छुट्टी पर",
    lastSeen: "अंतिम बार देखा",
    location: "स्थान",
    role: "भूमिका",
    updateLocation: "स्थिति अपडेट करें",
    filterDept: "विभाग से फ़िल्टर करें",
    filterStatus: "स्थिति से फ़िल्टर करें",
    allDepts: "सभी जोन",
    allStatuses2: "सभी स्थितियाँ",
    OnSite: "साइट पर",
    Remote: "दूरस्थ",
    OnLeave: "छुट्टी पर",
    saveLocation: "स्थान सुरक्षित करें",
    mapView: "मानचित्र दृश्य",
    gridView: "ग्रिड दृश्य",

    // ग्राहक प्रतिक्रिया मॉड्यूल
    navFeedback: "ग्राहक प्रतिक्रिया",
    feedbackTitle: "रिकवरी विजिट लॉग",
    feedbackSub: "प्रत्येक उधारकर्ता संपर्क प्रयास के लिए एजेंट विजिट परिणाम। संग्रह, वादे और एस्केलेशन लॉग करें।",
    totalFeedback: "कुल विजिट",
    avgRating: "औसत रिकवरी",
    positiveRate: "संग्रह दर",
    pendingReviews: "अनुवर्ती लंबित",
    addFeedback: "विजिट लॉग करें",
    customerName: "उधारकर्ता का नाम",
    loanRefIdFb: "ऋण आईडी",
    rating: "राशि (₹)",
    category: "परिणाम",
    comment: "एजेंट नोट्स",
    feedbackDate: "विजिट तिथि",
    feedbackStatus: "स्थिति",
    Resolved: "संग्रहित",
    Pending2: "भुगतान का वादा",
    Archived: "एस्केलेट",
    Service: "पूर्ण भुगतान",
    Product: "आंशिक भुगतान",
    Process: "भुगतान का वादा",
    Staff: "मना किया",
    allCategories: "सभी परिणाम",
    resolveFeedback: "संग्रहित चिह्नित करें",
    archiveFeedback: "एस्केलेट करें",
    submitFeedback: "विजिट लॉग करें",
    feedbackPlaceholder: "उधारकर्ता की प्रतिक्रिया, परिस्थितियाँ, अगले कदम का वर्णन करें...",

    // ── रिकवरी डैशबोर्ड ────────────────────────────────────
    recoveryOverview: "रिकवरी ऑपरेशन अवलोकन",
    recoveryOverviewSub: "सक्रिय रिकवरी एजेंटों, अतिदेय पोर्टफोलियो और दैनिक संग्रह प्रदर्शन की निगरानी करें।",
    assignCase: "रिकवरी केस असाइन करें",
    totalOverduePortfolio: "अतिदेय पोर्टफोलियो",
    recoveredThisMonth: "इस माह रिकवर किया गया",
    recoveryRate: "रिकवरी दर",
    activeAgentsInField: "फील्ड में एजेंट",
    recoveryVsTarget: "रिकवरी बनाम लक्ष्य",
    recoveryVsTargetSub: "मासिक संग्रह बनाम रिकवरी लक्ष्य।",
    targetRecovery: "लक्ष्य",
    actualRecovery: "संग्रहित",
    casesByStatus: "स्थिति अनुसार केस",
    casesByStatusSub: "सभी असाइन किए गए रिकवरी केस का विवरण।",
    totalCases: "कुल केस",
    agentSummaryTitle: "आज ड्यूटी पर एजेंट",
    agentSummaryLink: "सभी एजेंट देखें",

    // ── रिकवरी केस टेबल ────────────────────────────────────
    recoveryCase: "रिकवरी केस",
    recoveryCaseSub: "संग्रह के लिए फील्ड रिकवरी एजेंटों को सौंपे गए अतिदेय ऋण केस।",
    daysOverdue: "अतिदेय दिन",
    assignedAgent: "असाइन एजेंट",
    recoveryStatus: "रिकवरी स्थिति",
    lastContact: "अंतिम संपर्क",
    Recovered: "रिकवर किया गया",
    InProgress: "प्रगति में",
    PendingContact: "संपर्क लंबित",
    Escalated: "एस्केलेट किया गया",
    allRecoveryStatuses: "सभी स्थितियाँ",

    // ── रिकवरी एजेंट मॉड्यूल ──────────────────────────────
    navRecoveryAgents: "रिकवरी एजेंट",
    recoveryAgentsTitle: "रिकवरी एजेंट",
    recoveryAgentsSub: "फील्ड रिकवरी एजेंटों, उनके जोन, केसलोड और संग्रह प्रदर्शन का प्रबंधन करें।",
    addAgent: "एजेंट जोड़ें",
    agentId: "एजेंट आईडी",
    agentName: "एजेंट का नाम",
    zone: "जोन",
    casesAssigned: "असाइन केस",
    recoveredAmount: "रिकवर (₹)",
    successRate: "सफलता दर",
    agentStatus: "स्थिति",
    totalAgents: "कुल एजेंट",
    activeAgents: "सक्रिय एजेंट",
    topPerformer: "शीर्ष प्रदर्शक",
    avgSuccessRate: "औसत सफलता दर",
    saveAgent: "एजेंट सहेजें",
    contactNumber: "संपर्क नंबर",
    assignedZone: "असाइन जोन",
    joinDate: "जॉइन तिथि",

    // ── एजेंट उपस्थिति (रिकवरी) ───────────────────────────
    attendanceTitle: "एजेंट उपस्थिति",
    attendanceSub: "जोन अनुसार सभी रिकवरी एजेंटों के लिए दैनिक फील्ड ड्यूटी चेक-इन ट्रैक करें।",
    markAttendance: "उपस्थिति दर्ज करें",
    totalEmployees: "कुल एजेंट",
    presentToday: "आज ड्यूटी पर",
    absentToday: "आज ऑफ ड्यूटी",
    lateArrivals: "देर से फील्ड पहुंचे",
    department: "जोन",
    allDepts: "सभी जोन",
    attendanceNote: "फील्ड चेक-इन डेटा हर 10 मिनट में मोबाइल एजेंट ऐप के साथ स्वतः सिंक होता है।",

    // ── एजेंट फील्ड घंटे ───────────────────────────────────
    workingHoursTitle: "एजेंट फील्ड घंटे",
    workingHoursSub: "रिकवरी जोन में साप्ताहिक फील्ड घंटे, ओवरटाइम और कम समय की निगरानी करें।",
    weeklyBreakdownSub: "वर्तमान सप्ताह के लिए जोन-स्तरीय फील्ड घंटे।",

    // ── एजेंट लाइव ट्रैकिंग ─────────────────────────────────
    trackingTitle: "एजेंट लाइव ट्रैकिंग",
    trackingSub: "रिकवरी एजेंटों के फील्ड स्थानों और सक्रिय केस असाइनमेंट में रीयल-टाइम दृश्यता।",
    totalStaff: "कुल एजेंट",
    currentCase: "वर्तमान केस",
    loanId: "ऋण आईडी",
    updateLocation: "स्थिति अपडेट करें",
    mapView: "मानचित्र दृश्य",
    gridView: "ग्रिड दृश्य",

    // ── रिकवरी विजिट लॉग ──────────────────────────────────
    feedbackTitle: "रिकवरी विजिट लॉग",
    feedbackSub: "प्रत्येक उधारकर्ता संपर्क प्रयास के लिए एजेंट विजिट परिणाम। संग्रह, वादे और एस्केलेशन लॉग करें।",
    totalFeedback: "कुल विजिट",
    avgRating: "औसत रिकवरी",
    positiveRate: "संग्रह दर",
    pendingReviews: "अनुवर्ती लंबित",
    addFeedback: "विजिट लॉग करें",
    customerName: "उधारकर्ता का नाम",
    loanRefIdFb: "ऋण आईडी",
    rating: "राशि (₹)",
    category: "परिणाम",
    comment: "एजेंट नोट्स",
    feedbackDate: "विजिट तिथि",
    feedbackStatus: "स्थिति",
    Resolved: "संग्रहित",
    Pending2: "भुगतान का वादा",
    Archived: "एस्केलेट",
    Service: "पूर्ण भुगतान",
    Product: "आंशिक भुगतान",
    Process: "भुगतान का वादा",
    Staff: "मना किया",
    allCategories: "सभी परिणाम",
    resolveFeedback: "संग्रहित चिह्नित करें",
    archiveFeedback: "एस्केलेट करें",
    submitFeedback: "विजिट लॉग करें",
    // new data
    feedbackPlaceholder: "उधारकर्ता की प्रतिक्रिया, परिस्थितियाँ, अगले कदम का वर्णन करें...",
  },
};

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("apex-theme") || "dark";
    }
    return "dark";
  });

  const [language, setLanguage] = useState(() => {
    if (typeof window !== "undefined") {
      return localStorage.getItem("apex-language") || "en";
    }
    return "en";
  });

  // Sync theme to document element and persist to localStorage
  useEffect(() => {
    const root = window.document.documentElement;
    if (theme === "dark") {
      root.classList.add("dark");
    } else {
      root.classList.remove("dark");
    }
    localStorage.setItem("apex-theme", theme);
  }, [theme]);

  // Persist language to localStorage
  useEffect(() => {
    localStorage.setItem("apex-language", language);
  }, [language]);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "dark" ? "light" : "dark"));
  };

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "hi" : "en"));
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <AppContext.Provider
      value={{
        theme,
        toggleTheme,
        language,
        setLanguage,
        toggleLanguage,
        t,
      }}
    >
      {children}
    </AppContext.Provider>
  );
}

export function useApp() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error("useApp must be used within an AppProvider");
  }
  return context;
}
